# cspell:ignore schneegans
name: Verification

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v6
      - name: Test with pytest
        run: coverage run --data-file reports/.coverage -m pytest -v -s
      - name: Generate Coverage Report Summary
        run: coverage report -m --data-file reports/.coverage --format=markdown --include=custom_components/** >> $GITHUB_STEP_SUMMARY
      - name: Generate Coverage Report
        run: coverage json --data-file reports/.coverage -o reports/coverage.json --include=custom_components/**
      - name: Get coverage output
        id: coverage
        run: echo "value=$(node -e "const fs = require('node:fs'), x = JSON.parse(fs.readFileSync('reports/coverage.json')); console.log(Math.round(x.totals.percent_covered * 100)/ 100);")" >> "$GITHUB_OUTPUT"
      - name: Coverage to badge
        if: github.event_name == 'push'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 03ba5cb1f9f017852a3d910a8df02fc4
          filename: home-assistant-gpio-integration.svg
          label: Test Coverage
          message: ${{ steps.coverage.outputs.value }}
          color: green
          namedLogo: pytest
          forceUpdate: true
